language: go
go:
- 1.6.2
env:
  global:
  - PATH=~/gopath/bin:$PATH
  - DEBIAN_FRONTEND=noninteractive
  - secure: "JFcsVSj4tI+yz9nu3qTgcWs0VwtUgOBIymH4qw6/ns+S3wcGuBXTgMxd9inIY/qUZhTHDzKMB44OxCwMXyqYKj+o9fe96Vs6tpKJU9XZWa2LvWeegSyA1dA60yMs3L73gTy0ASJC5wRGZTTa9dlqUNYxH7i8M6v1tz4tc9uUM7md+am6Cct5FZlGrYnmV70iLkVhb9nQKRVzgjh2AamgOFekSO4S0cxZe9VwO1tdJ26F/fWpOk2P5maRfQbOE7cQh+1v/NdgsO/fu/kZvcXE5CEerx/dXDudJnNEfIn6qbg4bbhbb3cFi9pBeokp1dSte/53tFDS1llHjoNeSx8JSgtgS6Xe0T5NuMquVe7sKPT9v9ysXBxH5VdvOc+kmvSTCePuNFHcH/sv11gkyQqhSZtEPEodegbkb5EGPkGgLGA9Puagb/1nzEN5e1ZwaiX9xadXTIzBduPYLKqo/vRfXA+Kg0CJ/LNwTCwmigcJNOA2OQP+osCvmseQegO7cUUccmL4DyGsx1QAwNFMaw5gVYiEDCZYKtr6PirkymzLQeQa7VvYxk5qh9cQEUGcnmnpmlVSkT6yhqAZWbm4CWOQVSHiY5+2jHR2oL5NH0PE2qWXLUhG/XgYQa09qN3qxiv7ALs+tbh8rIB4S7AonGsSgdFyx3ITfnrdThI4JFG88J8="
sudo: false
addons:
  apt:
    packages:
    - rpm
    - devscripts
    - debhelper
    - jq
install:
- go get github.com/mitchellh/gox
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make lint
- make cover
- make all
after_script:
- goveralls -coverprofile=.profile.cov
before_deploy:
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=100 || true
- git fetch --tags --depth=100 || true
deploy:
- provider: script
  script: tool/releng --task=upload-to-github-release && tool/releng --task=upload-master-to-github-release
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: tool/releng --task=create-pullrequest --current-branch=$TRAVIS_BRANCH --package-name=mackerel-check-plugins
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
notifications:
  slack:
    secure: W4637ZIl5Gbwm93btsfysyvZpVw3GVMni1y7ea8lj4XFEyNV9aoW0OIkCjWIL9MrkxnkCcnhTKfOAPuFoqFYXXRJFkYCU9GYRsENqwvk9ev2xNyQ9OPIdNqVFcgzA4qiX97JwiuvkaDauRLsWKpdZUtMugrMEsnt1hH6E6uJ5CyVtuun9O5SyICet9tzyLyFpefrhKT8LJiwYDzT9PX6vaL2FCxDgservpPon4YkIkbaZcfURbkd0Gkm3IW5HSVAzAesEspDPAAbMp0ZKF6YPXk1kCuAttNcXoNfRyxIWD02qYTVvVLMVI9DbcDGzAeBPYaZ0vLFtCTwPWx342GqAVDy1sZ5xqYwwqpeVwPA7GdCARl3PgP1q04j4Dd6ZUMn5vM+HdMGtbKcT2vks/t9D8ozrX2F/SyTAVCVqt4xEBSVus4U8a7oK+JQXphnV++8ltDfyXoSdv4oQjHDmpZurcbEgmzWBFuenQK8CKM71voEZZSxhu4/7TksoXuo0zzxhopR9u9B/Y+/74azGBv3VW/JfzJ5gzi08Y56YA80pLHjbxJeykKzv4lR+c+WAWGxVhBD9xN4OKcer3ohDbTfhs0rDf270DOSYx3bstnvQ87NcNbJ1sPRwRhK8rbzvwtLnGUjMNK1kNRcr2rQmmJYlR3DH/hfHHEvAQPeseN90Ek=
