# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    # Look for a Go Modules to update in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "hourly"
