---
name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: ["1.14.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt-get install memcached
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: |
          make lint
          make cover
          # goveralls -coverprofile=.profile.cov

  test-windows:
    strategy:
      matrix:
        go: ["1.14.x"]
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: |
          go build -o check-log/check-log.exe ./check-log
          go build -o check-procs/check-procs.exe ./check-procs
          go build -o check-windows-eventlog/check-windows-evenglog.exe ./check-windows-eventlog
          go vet -all ./check-log/... ./check-procs/... ./check-ntservice/... ./check-windows-eventlog/...
          go test ./check-log/... ./check-procs/... ./check-ntservice/... ./check-windows-eventlog/...
