---
name: test

"on": [pull_request, push]

# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        go: ["1.14"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          docker run -d -p 11211:50081 --rm memcached:1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: |
          make lint
          make cover
          # goveralls -coverprofile=.profile.cov

  test-windows:
    strategy:
      matrix:
        go: ["1.14"]
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: |
          go get -d -v -t ./...
          go build -o check-log/check-log.exe ./check-log
          go build -o check-procs/check-procs.exe ./check-procs
          go build -o check-windows-eventlog/check-windows-evenglog.exe ./check-windows-eventlog
          go vet -all ./check-log/... ./check-procs/... ./check-ntservice/... ./check-windows-eventlog/...
          go test ./check-log/... ./check-procs/... ./check-ntservice/... ./check-windows-eventlog/...
